/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Oscar R (https://sketchfab.com/braidoner)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/star-wars-low-poly-hoth-skybox-caddf0ec811a47d5a2449a4d076a9d7b
Title: Star Wars - Low Poly Hoth Skybox
*/

// import React, {useRef} from 'react';
import {useGLTF} from '@react-three/drei';
import skyBox from '../../assets/3d/skybox.glb';
//
// export function Model(props) {
//     const {nodes, materials} = useGLTF('/skybox.glb');
//     return (
//         <group {...props} dispose={null}>
//             <mesh
//                 geometry={nodes.hoth_sky_lambert1_0.geometry}
//                 material={materials.lambert1}
//                 scale={267.253}
//             />
//             <mesh
//                 geometry={nodes.cloud17_lambert1_0.geometry}
//                 material={materials.lambert1}
//                 position={[204.159, -227.504, 47.945]}
//                 rotation={[0, -0.283, -3.106]}
//                 scale={4.082}
//             />
//             <mesh
//                 geometry={nodes.cloud18_lambert1_0.geometry}
//                 material={materials.lambert1}
//                 position={[113.759, 252.834, -176.519]}
//                 rotation={[-0.06, 0.944, -3.085]}
//                 scale={4.082}
//             />
//             <mesh geometry={nodes.clouds2_lambert1_0.geometry} material={materials.lambert1}/>
//         </group>
//     );
// }


export const Sky = () => {
    const sky = useGLTF(skyBox);

    return (
        <mesh>
            <primitive object={sky.scene}/>
        </mesh>
    );
};
