/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Oscar R (https://sketchfab.com/braidoner)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/star-wars-low-poly-hoth-skybox-caddf0ec811a47d5a2449a4d076a9d7b
Title: Star Wars - Low Poly Hoth Skybox
*/

// import React, {useRef} from 'react';
import {useGLTF} from '@react-three/drei';
import skyBox from '../../assets/3d/skybox.glb';
import {useRef} from "react";
import {useFrame} from "@react-three/fiber";

// eslint-disable-next-line react/prop-types
export const Sky = ({isRotating}) => {
    const ref = useRef();
    const sky = useGLTF(skyBox);

    useFrame((_, delta) => {
        if (isRotating) {
            ref.current.rotation.y += 0.05 * delta;
        }
    });

    return (
        <mesh ref={ref}>
            <primitive object={sky.scene}/>
        </mesh>
    );
};
